server {
    listen 443 ssl;
    index index.php index.html;
    root CONFIG_WORDPRESS_PATH;
    server_name CONFIG_DOMAIN_NAME;

    # This should fix the mapping mismatch of ports
    absolute_redirect off;


    ssl_certificate /etc/nginx/ssl/nginx.crt;
    ssl_certificate_key /etc/nginx/ssl/nginx.key;

    ssl_protocols TLSv1.2 TLSv1.3;

    location / {
        try_files $uri $uri/ /index.php?$args;
    }

    location ~ \.php$ {
        include fastcgi.conf;

        fastcgi_pass wordpress:9000;
    }

    location /adminer {
        include fastcgi.conf;
        fastcgi_param  SCRIPT_FILENAME /var/index.php;
        fastcgi_pass adminer:9000;
    }

    location /game/ {
        proxy_pass http://game:80/;
    }

    location /portainer/ {
    	proxy_pass http://portainer:9000/;
    }

}
