server {
    listen 80;
    index index.php index.html;
    root /var/www/html;

    # This should fix the mapping mismatch of ports
    absolute_redirect off;

    location / {
        try_files $uri $uri/ /index.php?$args;
    }

    location ~ \.php$ {
        include fastcgi.conf;

        fastcgi_pass wordpress:9000;
    }

    location /adminer {
        include fastcgi.conf;
        fastcgi_param  SCRIPT_FILENAME /var/index.php;
        fastcgi_pass adminer:9000;
    }

    location /resume {
        proxy_pass http://resume:80/;
    }

}
