server {
    listen 8080;
    index index.php index.html;
    root /var/www/html;

    location / {
        try_files $uri $uri/ /index.php?$args;
    }

    location ~ \.php$ {
        # NOTE: You should have "cgi.fix_pathinfo = 0;" in php.ini
        include fastcgi.conf;
        # fastcgi_intercept_errors on;
        fastcgi_pass wordpress:9000;
    }
}
