services:
  ftp:
    build: requirements/bonus/ftp
    ports:
      - "9090:21"
      - "21000-21010:21000-21010"
    networks:
      - localnet
    volumes:
      - wordpress_source:${VOLUME_GUEST_PATH}
    environment:
      FTP_PASSWORD_FILE: /run/secrets/ftp_password
      FTP_DIRECTORY: ${VOLUME_GUEST_PATH}
      FTP_USERNAME: liri
    secrets:
     - ftp_password

  nginx:
    build: requirements/nginx
    ports:
      - "8080:80"
    networks:
      - localnet
    volumes:
      - wordpress_source:${VOLUME_GUEST_PATH}
      - nginx_logs:/var/log/nginx
    depends_on:
      - wordpress

  goaccess:
    build: requirements/bonus/goaccess
    ports:
      - "9191:80"
      - "7890:7890"
    networks:
      - localnet
    volumes:
      - nginx_logs:/var/log/nginx:ro
      - wordpress_source:${VOLUME_GUEST_PATH}
    depends_on:
      - nginx
      - wordpress

  resume:
    build: requirements/bonus/resume
    networks:
      - localnet

  adminer:
    build: requirements/bonus/adminer
    volumes:
      - wordpress_source:${VOLUME_GUEST_PATH}
    networks:
      - localnet
    depends_on:
      - mariadb
      - wordpress

  wordpress:
    build: requirements/wordpress
    env_file: .env
    volumes:
      - wordpress_source:${VOLUME_GUEST_PATH}
    secrets:
      - db_password
      - wp_admin_password
      - wp_auther_password
    networks:
      - localnet
    depends_on:
      - mariadb

  redis:
    build: requirements/bonus/redis
    networks:
      - localnet 

  mariadb:
    build: requirements/mariadb
    secrets:
     - db_password
    networks:
      - localnet 
    env_file: .env

networks:
  localnet:
    driver: bridge

volumes:
  wordpress_source:
  nginx_logs:
secrets:
   db_password:
     file: ../secrets/db_password.txt
   wp_admin_password:
     file: ../secrets/wp_admin_password.txt
   wp_auther_password:
     file: ../secrets/wp_user_password.txt
   ftp_password:
     file: ../secrets/ftp_password.txt
