services:
  ftp:
    build: requirements/bonus/ftp
    ports:
      - "9090:21"
      - "21000-21010:21000-21010"
    networks:
      - localnet
    volumes:
      - wordpress_source:/var/www/html
    environment:
      FTP_PASSWORD_FILE: /run/secrets/ftp_password
      FTP_DIRECTORY: /var/www/html
      FTP_USERNAME: liri
    secrets:
     - ftp_password

  nginx:
    build: requirements/nginx
    ports:
      - "8080:80"
    networks:
      - localnet
    volumes:
      - wordpress_source:/var/www/html
    depends_on:
      - wordpress

  resume:
    build: requirements/bonus/resume
    networks:
      - localnet

  adminer:
    build: requirements/bonus/adminer
    volumes:
      - wordpress_source:/var/www/html
    networks:
      - localnet
    depends_on:
      - mariadb
      - wordpress

  wordpress:
    build: requirements/wordpress
    environment:
      MARIADB_HOST: mariadb
      MARIADB_USER_NAME: liri
      MARIADB_USER_DATABASE: wordpress
      MARIADB_USER_PASSWORD_FILE: /run/secrets/db_password
      WP_URL: http://localhost:8080
      WP_TITLE: Wordpress
      WP_ADMIN_USER: root
      WP_ADMIN_PASSWORD_FILE: /run/secrets/wp_admin_password
      WP_ADMIN_EMAIL: root@example.com
      WP_USER: liri
      WP_USER_PASSWORD_FILE: /run/secrets/wp_user_password
      WP_USER_EMAIL: liri@example.com
    volumes:
      - wordpress_source:/var/www/html
    secrets:
      - db_password
      - wp_admin_password
      - wp_user_password
    networks:
      - localnet
    depends_on:
      - mariadb

  redis:
    build: requirements/bonus/redis
    networks:
      - localnet 

  mariadb:
    build: requirements/mariadb
    environment:
      MARIADB_USER_NAME: liri
      MARIADB_USER_DATABASE: wordpress
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MARIADB_USER_PASSWORD_FILE: /run/secrets/db_password
    secrets:
     - db_root_password
     - db_password
    networks:
      - localnet 

networks:
  localnet:
    driver: bridge

volumes:
  wordpress_source:

secrets:
   db_password:
     file: ../secrets/db_password.txt
   db_root_password:
     file: ../secrets/db_root_password.txt
   wp_admin_password:
     file: ../secrets/wp_admin_password.txt
   wp_user_password:
     file: ../secrets/wp_user_password.txt
   ftp_password:
     file: ../secrets/ftp_password.txt
