services:
  nginx:
    restart: always
    build: 
      context: requirements/nginx
      args:
        - DOMAIN_NAME=${DOMAIN_NAME}
    image: nginx
    ports:
      - "443:443"
    networks:
      - localnet
    volumes:
      - wordpress_source:${WP_DATA_CONTAINER}
    env_file: .env
    depends_on:
      - wordpress

  wordpress:
    restart: always
    build:
      context: requirements/wordpress
      args:
        - WORDPRESS_PATH=${WORDPRESS_PATH}
    image: wordpress
    env_file: .env
    volumes:
      - wordpress_source:${WP_DATA_CONTAINER}
    secrets:
      - db_password
      - wp_admin_password
      - wp_auther_password
    networks:
      - localnet
    depends_on:
      - mariadb
      - redis

  mariadb:
    restart: always
    build: requirements/mariadb
    image: mariadb
    secrets:
     - db_password
    networks:
      - localnet
    volumes:
      - DB:/var/lib/mysql
    env_file: .env

  # ------------------------------- Bonus -------------------------------

  ftp:
    restart: always
    image: ftp
    build: requirements/bonus/ftp
    ports:
      - "21:21"
      - "21000-21010:21000-21010"
    networks:
      - localnet
    volumes:
      - wordpress_source:${WP_DATA_CONTAINER}
    env_file: .env
    secrets:
     - ftp_password

  portainer:
    build: ./requirements/bonus/portainer
    image: portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - localnet
    restart: always

  game:
    restart: always
    image: game
    build: requirements/bonus/game
    networks:
      - localnet

  adminer:
    restart: always
    image: adminer
    build: requirements/bonus/adminer
    volumes:
      - wordpress_source:${WP_DATA_CONTAINER}
    networks:
      - localnet
    depends_on:
      - mariadb

  redis:
    restart: always
    image: redis
    build: requirements/bonus/redis
    networks:
      - localnet 

networks:
  localnet:
    driver: bridge

volumes:
  wordpress_source:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/aljbari/data/wordpress
  DB:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/aljbari/data/db

secrets:
   db_password:
     file: ../secrets/db_password.txt
   wp_admin_password:
     file: ../secrets/wp_admin_password.txt
   wp_auther_password:
     file: ../secrets/wp_user_password.txt
   ftp_password:
     file: ../secrets/ftp_password.txt
