# NOTE: http://vsftpd.beasts.org/vsftpd_conf.html

anonymous_enable=NO
local_enable=YES
guest_enable=YES
guest_username=nobody
write_enable=YES
virtual_use_local_privs=YES

chroot_local_user=YES
allow_writeable_chroot=YES

userlist_enable=YES
userlist_deny=NO

xferlog_enable=YES
vsftpd_log_file=/proc/1/fd/1


listen=YES
background=NO


ftpd_banner=Welcome to inception ftp server!

pasv_min_port=21000
pasv_max_port=21010

seccomp_sandbox=NO
